/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Fri Jun 03 15:58:02 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo.pojos;

public class AutoKey implements java.io.Serializable, Cloneable {
    /* matricula */
    protected String matricula;

    /* matricula */
    public String getMatricula() {
        return matricula;
    }

    /* matricula */
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (matricula != null)  
            hashCode += matricula.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof AutoKey))
            return false;

        AutoKey key = (AutoKey) obj;

        if (this.matricula == null) {
            if (key.matricula != null)
                return false;
        }
        else if (!this.matricula.equals(key.matricula)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        AutoKey key = new AutoKey();
        key.matricula = this.matricula;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("matricula").append(" = ").append(matricula).append("]");
        return sb.toString();
    }
}