/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Fri Jun 03 15:58:02 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo.pojos;

public class ClienteKey implements java.io.Serializable, Cloneable {
    /* idCliente */
    protected int idcliente;

    /* idCliente */
    public int getIdcliente() {
        return idcliente;
    }

    /* idCliente */
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(idcliente).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof ClienteKey))
            return false;

        ClienteKey key = (ClienteKey) obj;

        if (this.idcliente != key.idcliente)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        ClienteKey key = new ClienteKey();
        key.idcliente = this.idcliente;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idcliente").append(" = ").append(idcliente).append("]");
        return sb.toString();
    }
}