/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Fri Jun 03 15:58:02 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo.pojos;

public class CompraKey implements java.io.Serializable, Cloneable {
    /* idCompra */
    protected int idcompra;

    /* idCompra */
    public int getIdcompra() {
        return idcompra;
    }

    /* idCompra */
    public void setIdcompra(int idcompra) {
        this.idcompra = idcompra;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(idcompra).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof CompraKey))
            return false;

        CompraKey key = (CompraKey) obj;

        if (this.idcompra != key.idcompra)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        CompraKey key = new CompraKey();
        key.idcompra = this.idcompra;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idcompra").append(" = ").append(idcompra).append("]");
        return sb.toString();
    }
}