/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Fri Jun 03 15:58:02 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo.pojos;

/*
 * For Table compra
 */
public class Compra implements java.io.Serializable, Cloneable {
    private CompraKey _key = new CompraKey();

    /* idCompra, PK */
    protected int idcompra;

    /* fechaCompra */
    protected java.util.Date fechacompra;

    /* precioCompra */
    protected float preciocompra;

    /* idDistribuidor */
    protected int iddistribuidor;

    /* matricula */
    protected String matricula;

    /* Return the key object. */
    public CompraKey getKeyObject() {
        return _key;
    }

    /* idCompra, PK */
    public int getIdcompra() {
        return idcompra;
    }

    /* idCompra, PK */
    public void setIdcompra(int idcompra) {
        this.idcompra = idcompra;
        _key.setIdcompra(idcompra);
    }

    /* fechaCompra */
    public java.util.Date getFechacompra() {
        return fechacompra;
    }

    /* fechaCompra */
    public void setFechacompra(java.util.Date fechacompra) {
        this.fechacompra = fechacompra;
    }

    /* precioCompra */
    public float getPreciocompra() {
        return preciocompra;
    }

    /* precioCompra */
    public void setPreciocompra(float preciocompra) {
        this.preciocompra = preciocompra;
    }

    /* idDistribuidor */
    public int getIddistribuidor() {
        return iddistribuidor;
    }

    /* idDistribuidor */
    public void setIddistribuidor(int iddistribuidor) {
        this.iddistribuidor = iddistribuidor;
    }

    /* matricula */
    public String getMatricula() {
        return matricula;
    }

    /* matricula */
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Compra))
            return false;

        Compra bean = (Compra) obj;

        if (this.idcompra != bean.idcompra)
            return false;

        if (this.fechacompra == null) {
            if (bean.fechacompra != null)
                return false;
        }
        else if (!this.fechacompra.equals(bean.fechacompra)) 
            return false;

        if (this.preciocompra != bean.preciocompra)
            return false;

        if (this.iddistribuidor != bean.iddistribuidor)
            return false;

        if (this.matricula == null) {
            if (bean.matricula != null)
                return false;
        }
        else if (!this.matricula.equals(bean.matricula)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Compra bean = new Compra();
        bean.idcompra = this.idcompra;
        if (this.fechacompra != null)
            bean.fechacompra = (java.util.Date) this.fechacompra.clone();
        bean.preciocompra = this.preciocompra;
        bean.iddistribuidor = this.iddistribuidor;
        bean.matricula = this.matricula;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idcompra").append(" = ").append(idcompra).append("]").append(sep);
        sb.append("[").append("fechacompra").append(" = ").append(fechacompra).append("]").append(sep);
        sb.append("[").append("preciocompra").append(" = ").append(preciocompra).append("]").append(sep);
        sb.append("[").append("iddistribuidor").append(" = ").append(iddistribuidor).append("]").append(sep);
        sb.append("[").append("matricula").append(" = ").append(matricula).append("]").append(sep);
        return sb.toString();
    }
}