/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Fri Jun 03 15:58:02 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo.pojos;

public class DistribuidorKey implements java.io.Serializable, Cloneable {
    /* idDistribuidor */
    protected int iddistribuidor;

    /* idDistribuidor */
    public int getIddistribuidor() {
        return iddistribuidor;
    }

    /* idDistribuidor */
    public void setIddistribuidor(int iddistribuidor) {
        this.iddistribuidor = iddistribuidor;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(iddistribuidor).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof DistribuidorKey))
            return false;

        DistribuidorKey key = (DistribuidorKey) obj;

        if (this.iddistribuidor != key.iddistribuidor)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        DistribuidorKey key = new DistribuidorKey();
        key.iddistribuidor = this.iddistribuidor;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("iddistribuidor").append(" = ").append(iddistribuidor).append("]");
        return sb.toString();
    }
}