/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Fri Jun 03 15:58:02 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo.pojos;

/*
 * For Table distribuidor
 */
public class Distribuidor implements java.io.Serializable, Cloneable {
    private DistribuidorKey _key = new DistribuidorKey();

    /* idDistribuidor, PK */
    protected int iddistribuidor;

    /* nombreDistribuidor */
    protected String nombredistribuidor;

    /* cuidadDistribuidor */
    protected String cuidaddistribuidor;

    /* direccionDistribuidor */
    protected String direcciondistribuidor;

    /* telefonoDistribuidor */
    protected String telefonodistribuidor;

    /* Return the key object. */
    public DistribuidorKey getKeyObject() {
        return _key;
    }

    /* idDistribuidor, PK */
    public int getIddistribuidor() {
        return iddistribuidor;
    }

    /* idDistribuidor, PK */
    public void setIddistribuidor(int iddistribuidor) {
        this.iddistribuidor = iddistribuidor;
        _key.setIddistribuidor(iddistribuidor);
    }

    /* nombreDistribuidor */
    public String getNombredistribuidor() {
        return nombredistribuidor;
    }

    /* nombreDistribuidor */
    public void setNombredistribuidor(String nombredistribuidor) {
        this.nombredistribuidor = nombredistribuidor;
    }

    /* cuidadDistribuidor */
    public String getCuidaddistribuidor() {
        return cuidaddistribuidor;
    }

    /* cuidadDistribuidor */
    public void setCuidaddistribuidor(String cuidaddistribuidor) {
        this.cuidaddistribuidor = cuidaddistribuidor;
    }

    /* direccionDistribuidor */
    public String getDirecciondistribuidor() {
        return direcciondistribuidor;
    }

    /* direccionDistribuidor */
    public void setDirecciondistribuidor(String direcciondistribuidor) {
        this.direcciondistribuidor = direcciondistribuidor;
    }

    /* telefonoDistribuidor */
    public String getTelefonodistribuidor() {
        return telefonodistribuidor;
    }

    /* telefonoDistribuidor */
    public void setTelefonodistribuidor(String telefonodistribuidor) {
        this.telefonodistribuidor = telefonodistribuidor;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Distribuidor))
            return false;

        Distribuidor bean = (Distribuidor) obj;

        if (this.iddistribuidor != bean.iddistribuidor)
            return false;

        if (this.nombredistribuidor == null) {
            if (bean.nombredistribuidor != null)
                return false;
        }
        else if (!this.nombredistribuidor.equals(bean.nombredistribuidor)) 
            return false;

        if (this.cuidaddistribuidor == null) {
            if (bean.cuidaddistribuidor != null)
                return false;
        }
        else if (!this.cuidaddistribuidor.equals(bean.cuidaddistribuidor)) 
            return false;

        if (this.direcciondistribuidor == null) {
            if (bean.direcciondistribuidor != null)
                return false;
        }
        else if (!this.direcciondistribuidor.equals(bean.direcciondistribuidor)) 
            return false;

        if (this.telefonodistribuidor == null) {
            if (bean.telefonodistribuidor != null)
                return false;
        }
        else if (!this.telefonodistribuidor.equals(bean.telefonodistribuidor)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Distribuidor bean = new Distribuidor();
        bean.iddistribuidor = this.iddistribuidor;
        bean.nombredistribuidor = this.nombredistribuidor;
        bean.cuidaddistribuidor = this.cuidaddistribuidor;
        bean.direcciondistribuidor = this.direcciondistribuidor;
        bean.telefonodistribuidor = this.telefonodistribuidor;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("iddistribuidor").append(" = ").append(iddistribuidor).append("]").append(sep);
        sb.append("[").append("nombredistribuidor").append(" = ").append(nombredistribuidor).append("]").append(sep);
        sb.append("[").append("cuidaddistribuidor").append(" = ").append(cuidaddistribuidor).append("]").append(sep);
        sb.append("[").append("direcciondistribuidor").append(" = ").append(direcciondistribuidor).append("]").append(sep);
        sb.append("[").append("telefonodistribuidor").append(" = ").append(telefonodistribuidor).append("]").append(sep);
        return sb.toString();
    }
}