/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Fri Jun 03 15:58:02 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo.pojos;

public class VentaKey implements java.io.Serializable, Cloneable {
    /* idVenta */
    protected int idventa;

    /* idVenta */
    public int getIdventa() {
        return idventa;
    }

    /* idVenta */
    public void setIdventa(int idventa) {
        this.idventa = idventa;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(idventa).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof VentaKey))
            return false;

        VentaKey key = (VentaKey) obj;

        if (this.idventa != key.idventa)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        VentaKey key = new VentaKey();
        key.idventa = this.idventa;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idventa").append(" = ").append(idventa).append("]");
        return sb.toString();
    }
}