/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Fri Jun 03 15:58:02 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo.pojos;

/*
 * For Table venta
 */
public class Venta implements java.io.Serializable, Cloneable {
    private VentaKey _key = new VentaKey();

    /* idVenta, PK */
    protected int idventa;

    /* fechaVenta */
    protected String fechaventa;

    /* precioVenta */
    protected String precioventa;

    /* matricula */
    protected String matricula;

    /* rfcCliente */
    protected int rfccliente;

    /* numEmpleado */
    protected int numempleado;

    /* Return the key object. */
    public VentaKey getKeyObject() {
        return _key;
    }

    /* idVenta, PK */
    public int getIdventa() {
        return idventa;
    }

    /* idVenta, PK */
    public void setIdventa(int idventa) {
        this.idventa = idventa;
        _key.setIdventa(idventa);
    }

    /* fechaVenta */
    public String getFechaventa() {
        return fechaventa;
    }

    /* fechaVenta */
    public void setFechaventa(String fechaventa) {
        this.fechaventa = fechaventa;
    }

    /* precioVenta */
    public String getPrecioventa() {
        return precioventa;
    }

    /* precioVenta */
    public void setPrecioventa(String precioventa) {
        this.precioventa = precioventa;
    }

    /* matricula */
    public String getMatricula() {
        return matricula;
    }

    /* matricula */
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    /* rfcCliente */
    public int getRfccliente() {
        return rfccliente;
    }

    /* rfcCliente */
    public void setRfccliente(int rfccliente) {
        this.rfccliente = rfccliente;
    }

    /* numEmpleado */
    public int getNumempleado() {
        return numempleado;
    }

    /* numEmpleado */
    public void setNumempleado(int numempleado) {
        this.numempleado = numempleado;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Venta))
            return false;

        Venta bean = (Venta) obj;

        if (this.idventa != bean.idventa)
            return false;

        if (this.fechaventa == null) {
            if (bean.fechaventa != null)
                return false;
        }
        else if (!this.fechaventa.equals(bean.fechaventa)) 
            return false;

        if (this.precioventa == null) {
            if (bean.precioventa != null)
                return false;
        }
        else if (!this.precioventa.equals(bean.precioventa)) 
            return false;

        if (this.matricula == null) {
            if (bean.matricula != null)
                return false;
        }
        else if (!this.matricula.equals(bean.matricula)) 
            return false;

        if (this.rfccliente != bean.rfccliente)
            return false;

        if (this.numempleado != bean.numempleado)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Venta bean = new Venta();
        bean.idventa = this.idventa;
        bean.fechaventa = this.fechaventa;
        bean.precioventa = this.precioventa;
        bean.matricula = this.matricula;
        bean.rfccliente = this.rfccliente;
        bean.numempleado = this.numempleado;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idventa").append(" = ").append(idventa).append("]").append(sep);
        sb.append("[").append("fechaventa").append(" = ").append(fechaventa).append("]").append(sep);
        sb.append("[").append("precioventa").append(" = ").append(precioventa).append("]").append(sep);
        sb.append("[").append("matricula").append(" = ").append(matricula).append("]").append(sep);
        sb.append("[").append("rfccliente").append(" = ").append(rfccliente).append("]").append(sep);
        sb.append("[").append("numempleado").append(" = ").append(numempleado).append("]").append(sep);
        return sb.toString();
    }
}