/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Fri Jun 03 15:58:02 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo.pojos.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import com.ipn.mx.modelo.pojos.*;
import com.ipn.mx.modelo.dao.CompraDAO;

/**
 * This class provides methods to populate DB Table of compra
 */
public class CompraDAOImpl implements CompraDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO compra ("
        + "idCompra, fechaCompra, precioCompra, idDistribuidor, matricula"
        + ") VALUES (?, ?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "idCompra, fechaCompra, precioCompra, idDistribuidor, matricula "
        + "FROM compra WHERE "
        + "idCompra = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE compra SET "
        + "fechaCompra = ?, precioCompra = ?, idDistribuidor = ?, matricula = ? "
        + "WHERE "
        + "idCompra = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM compra WHERE "
        + "idCompra = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Compra bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setInt(1, bean.getIdcompra());
            if (bean.getFechacompra() != null)
                ps.setDate(2, new java.sql.Date(bean.getFechacompra().getTime()));
            else
                ps.setNull(2, Types.DATE);
            ps.setFloat(3, bean.getPreciocompra());
            ps.setInt(4, bean.getIddistribuidor());
            ps.setString(5, bean.getMatricula());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Compra load(CompraKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setInt(1, key.getIdcompra());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Compra) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Compra bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            if (bean.getFechacompra() != null)
                ps.setDate(1, new java.sql.Date(bean.getFechacompra().getTime()));
            else
                ps.setNull(1, Types.DATE);
            ps.setFloat(2, bean.getPreciocompra());
            ps.setInt(3, bean.getIddistribuidor());
            ps.setString(4, bean.getMatricula());
            ps.setInt(5, bean.getIdcompra());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(CompraKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setInt(1, key.getIdcompra());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    public List<Compra> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Compra>();
        while (rs.next()) {
            Compra bean = new Compra();
            bean.setIdcompra(rs.getInt("idCompra"));
            bean.setFechacompra(rs.getDate("fechaCompra"));
            bean.setPreciocompra(rs.getFloat("precioCompra"));
            bean.setIddistribuidor(rs.getInt("idDistribuidor"));
            bean.setMatricula(rs.getString("matricula"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}