/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Fri Jun 03 15:58:02 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo.pojos.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import com.ipn.mx.modelo.pojos.*;
import com.ipn.mx.modelo.dao.VendedorDAO;

/**
 * This class provides methods to populate DB Table of vendedor
 */
public class VendedorDAOImpl implements VendedorDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO vendedor ("
        + "numEmpleado, nombreEmpleado, apellidoEmpleado, usuario, contrasena, idDistribuidor"
        + ") VALUES (?, ?, ?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "numEmpleado, nombreEmpleado, apellidoEmpleado, usuario, contrasena, idDistribuidor "
        + "FROM vendedor WHERE "
        + "numEmpleado = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE vendedor SET "
        + "nombreEmpleado = ?, apellidoEmpleado = ?, usuario = ?, contrasena = ?, idDistribuidor = ? "
        + "WHERE "
        + "numEmpleado = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM vendedor WHERE "
        + "numEmpleado = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Vendedor bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setInt(1, bean.getNumempleado());
            ps.setString(2, bean.getNombreempleado());
            ps.setString(3, bean.getApellidoempleado());
            ps.setString(4, bean.getUsuario());
            ps.setString(5, bean.getContrasena());
            ps.setInt(6, bean.getIddistribuidor());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Vendedor load(VendedorKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setInt(1, key.getNumempleado());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Vendedor) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Vendedor bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getNombreempleado());
            ps.setString(2, bean.getApellidoempleado());
            ps.setString(3, bean.getUsuario());
            ps.setString(4, bean.getContrasena());
            ps.setInt(5, bean.getIddistribuidor());
            ps.setInt(6, bean.getNumempleado());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(VendedorKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setInt(1, key.getNumempleado());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Vendedor> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Vendedor>();
        while (rs.next()) {
            Vendedor bean = new Vendedor();
            bean.setNumempleado(rs.getInt("numEmpleado"));
            bean.setNombreempleado(rs.getString("nombreEmpleado"));
            bean.setApellidoempleado(rs.getString("apellidoEmpleado"));
            bean.setUsuario(rs.getString("usuario"));
            bean.setContrasena(rs.getString("contrasena"));
            bean.setIddistribuidor(rs.getInt("idDistribuidor"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}