/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Fri Jun 03 15:58:02 CDT 2016
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.ipn.mx.modelo.pojos.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import com.ipn.mx.modelo.pojos.*;
import com.ipn.mx.modelo.dao.VentaDAO;

/**
 * This class provides methods to populate DB Table of venta
 */
public class VentaDAOImpl implements VentaDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO venta ("
        + "idVenta, fechaVenta, precioVenta, matricula, rfcCliente, numEmpleado"
        + ") VALUES (?, ?, ?, ?, ?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "idVenta, fechaVenta, precioVenta, matricula, rfcCliente, numEmpleado "
        + "FROM venta WHERE "
        + "idVenta = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE venta SET "
        + "fechaVenta = ?, precioVenta = ?, matricula = ?, rfcCliente = ?, numEmpleado = ? "
        + "WHERE "
        + "idVenta = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM venta WHERE "
        + "idVenta = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Venta bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setInt(1, bean.getIdventa());
            ps.setString(2, bean.getFechaventa());
            ps.setString(3, bean.getPrecioventa());
            ps.setString(4, bean.getMatricula());
            ps.setInt(5, bean.getRfccliente());
            ps.setInt(6, bean.getNumempleado());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Venta load(VentaKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setInt(1, key.getIdventa());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Venta) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Venta bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getFechaventa());
            ps.setString(2, bean.getPrecioventa());
            ps.setString(3, bean.getMatricula());
            ps.setInt(4, bean.getRfccliente());
            ps.setInt(5, bean.getNumempleado());
            ps.setInt(6, bean.getIdventa());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(VentaKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setInt(1, key.getIdventa());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Venta> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Venta>();
        while (rs.next()) {
            Venta bean = new Venta();
            bean.setIdventa(rs.getInt("idVenta"));
            bean.setFechaventa(rs.getString("fechaVenta"));
            bean.setPrecioventa(rs.getString("precioVenta"));
            bean.setMatricula(rs.getString("matricula"));
            bean.setRfccliente(rs.getInt("rfcCliente"));
            bean.setNumempleado(rs.getInt("numEmpleado"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}